name: Test the code

on:
  workflow_call

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.6
      - name: Build
        run: go build -o tmp/grab main.go
      - name: Test
        run: go test -count=1 ./...
      - name: Lint
        run: golangci-lint run ./...
